### ISSUE TITLE
Bot does not issue any voice command, throws up TypeErrors.

### ISSUE THREAD

**Issue by EBMOfficial** [inevolin/DiscordSpeechBot#2]
This is a very frustrating issue and I have scoured every available resource to try and fix it, but I have not been able to fix it. I am using the exact same code provided here in this repository.  
![Screenshot from 2021-09-30 18-38-59](https://user-images.githubusercontent.com/63750451/135539424-d3f28604-5bb3-44df-932c-cef20a9ee497.png)
I basically issue a voice command, like here, I said "computer play take my breath the weekend audio", in an attempt to play a song. Instead, the bot throws up this error "Cannot use 'in' operator to search for '_text' in (the text field)". I am not sure if this is a Wit.ai problem or a problem with this script but I would really like a fix because these voice commands are used a lot on a daily basis by my Discord server and it's a huge disruption.

**Comment by SebSRVV** [comment]
have u fix it?
